GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/61e9816b4f64db91c4344141


###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "Amazing Person",
  "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/61e9816b4f64db91c4344141

###
PATCH http://localhost:3000/subscribers/61e9bc0a4f64db91c4344149
Content-Type: application/json

{
  "name": "New Name"
}